AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: vd-speed-test — Aggregator + Dashboard + Hourly Checker deployment

Globals:
  Function:
    Timeout: 300
    MemorySize: 512
    Runtime: python3.12
    Architectures: [x86_64]

Resources:
  # --- Daily Aggregator Lambda ---
  VdSpeedTestAggregator:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: vd-speedtest-daily-aggregator
      Handler: lambda_function.lambda_handler
      CodeUri: ./
      Description: Aggregates daily speed test data
      Policies:
        - S3FullAccessPolicy:
            BucketName: vd-speed-test
      FunctionUrlConfig:
        AuthType: NONE

  # --- EventBridge Daily Schedule ---
  DailyAggregationSchedule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: cron(30 0 * * ? *)  # At 00:30 AM UTC daily
      Targets:
        - Arn: !GetAtt VdSpeedTestAggregator.Arn
          Id: LambdaTarget
    DependsOn: VdSpeedTestAggregator

  # --- Permission for EventBridge to trigger Aggregator ---
  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref VdSpeedTestAggregator
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt DailyAggregationSchedule.Arn

  # --- Flask Dashboard Lambda (Mangum-based) ---
  VdSpeedTestDashboard:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: vd-speedtest-dashboard
      Handler: lambda_dashboard.lambda_handler
      CodeUri: ./
      Description: Flask dashboard for vd-speed-test
      Environment:
        Variables:
          S3_BUCKET: vd-speed-test
          AWS_REGION1: ap-south-1
      Policies:
        - S3ReadPolicy:
            BucketName: vd-speed-test
      FunctionUrlConfig:
        AuthType: NONE

  # --- Hourly Checker Lambda ---
  VdSpeedTestHourlyChecker:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: vd-speedtest-hourly-checker
      Handler: lambda_hourly_check.lambda_handler
      CodeUri: ./
      Description: Return hourly/minute folder count for a given date
      Environment:
        Variables:
          S3_BUCKET: vd-speed-test
          AWS_REGION1: ap-south-1
      Policies:
        - S3ReadPolicy:
            BucketName: vd-speed-test
      FunctionUrlConfig:
        AuthType: NONE

Outputs:
  AggregatorFunctionUrl:
    Description: "URL for Daily Aggregator Function"
    Value: !GetAtt VdSpeedTestAggregatorUrl.FunctionUrl

  DashboardFunctionUrl:
    Description: "URL for Dashboard Function"
    Value: !GetAtt VdSpeedTestDashboardUrl.FunctionUrl

  HourlyCheckerFunctionUrl:
    Description: "URL for Hourly Checker Function"
    Value: !GetAtt VdSpeedTestHourlyCheckerUrl.FunctionUrl


# deployment commands:
# sam build
# sam deploy --guided
# sam deploy --config-file samconfig.toml
# sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
# sam logs -n vd-speedtest-daily-aggregator --stack-name vd-speedtest-stack --tail
# sam logs -n vd-speedtest-dashboard --stack-name vd-speedtest-stack --tail
# sam logs -n vd-speedtest-hourly-checker --stack-name vd-speedtest-stack --tail
# aws lambda invoke --function-name vd-speedtest-daily-aggregator out.json
# aws lambda invoke --function-name vd-speedtest-dashboard out.json
# aws lambda invoke --function-name vd-speedtest-hourly-checker out.json